# Generated by Django 5.0.6 on 2024-06-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='bild',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
